## Numpy Array and Basics

In [2]:
import numpy as np

### Creating array from list

In [ ]:
"""1D Array"""
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array :", array_1d)

"""2D Array"""
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array :", array_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]]


### List vs Numpy

In [ ]:
"""Scalar multiplication"""

py_list = [1, 2, 3]
print("Python list multiplication :", py_list * 2) #list's elements gets repeated as per the passed scalar  

py_array = np.array([1, 2, 3])
print("Python array multiplication :", py_array * 2) #array's elements get multiplied with the scalar


"""Effeciency"""
import time

start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\nList operation time :", time.time() - start)

start = time.time()
py_array = np.arange(100000000) * 2
print("Numpy operation time :", time.time() - start) #numpy is optimized for array operations

Python list multiplication : [1, 2, 3, 1, 2, 3]
Python array multiplication : [2 4 6]

List operation time : 3.8149712085723877
Numpy operation time : 0.4176325798034668


### Creating array from scratch

In [38]:
"""Array of Zeros"""
zeros = np.zeros(4)
print("Array of Zeros :", zeros)

"""Array of Ones"""
ones = np.ones(4)
print("Array of Ones :", ones)

"""Array of Custom number"""
full = np.full(4, 7)
print("Array of custom number :", full)

"""Array of Random Numbers"""
random = np.random.random(4)
print("Array of random numbers :", random) #random values fluctuate b/w 1 and zeros 

"""Array of Sequence"""
sequence = np.arange(0, 10, 2)
print("Array of random numbers :", sequence)

Array of Zeros : [0. 0. 0. 0.]
Array of Ones : [1. 1. 1. 1.]
Array of custom number : [7 7 7 7]
Array of random numbers : [0.93577027 0.46320298 0.94567794 0.30767204]
Array of random numbers : [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
"""Vector"""
#An 1-Dimensional array is called Vector
vector = np.array([1, 2, 3, 4, 5])
print("Vector :", vector)

"""Matrix"""
#A 2-Dimensional (m x n) array is called Matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix :", matrix)

"""Tensor"""
#An array of more than 2-Dimensions is called Tensor
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("Tensor:", tensor)

Vector : [1 2 3 4 5]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


### Array properties

In [51]:
#There are various properties of array, some of them are :
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

#Data Type - '.dtype' is used to get data type of array .
print("Data Type :", arr.dtype)

#Size - '.size' is used to get the count of element in array .
print("Size :", arr.size)

#Dimension - '.ndim' is used to get the count of dimension of array .
print("Dimension :", arr.ndim)

#Shape - '.shape' is used to get the shape of array . 
print("Shape :", arr.shape)

Data Type : int64
Size : 18
Dimension : 3
Shape : (2, 3, 3)


### Array Transformations

In [11]:
#There are various transforming operations in array :
arr = np.arange(12)
print("Original array :", arr)

#Reshape - '.rehape' returns copy in desired shape
print("Reshaped array :", arr.reshape((3,4)))

updated_arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("\nUpdated array :", updated_arr)

#Flattend - '.flatten' returns copy in 1D array
print("Flattened array :", updated_arr.flatten())

#Ravel - '.ravel' returns given array in 1D array
print("Ravel array :", updated_arr.ravel())

#Transpose - '.T' returns Transpose of given matrix
print("Transpose array :", updated_arr.T)


Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Updated array : [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Flattened array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Ravel array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Transpose array : [[[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]

 [[ 3 12]
  [ 6 15]
  [ 9 18]]]
